"""add unique constraints to conversations table

Revision ID: 4ac90ce6a332
Revises: 71b31e7f778a
Create Date: 2026-06-21 20:55:58.810455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac90ce6a332'
down_revision: Union[str, Sequence[str], None] = '71b31e7f778a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user_id_low', sa.Integer(), nullable=False))
    op.add_column('conversations', sa.Column('user_id_high', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_conversation_pair', 'conversations', ['user_id_low', 'user_id_high'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_constraint('unique_conversation_pair', 'conversations', type_='unique')
    op.drop_column('conversations', 'user_id_high')
    op.drop_column('conversations', 'user_id_low')
    # ### end Alembic commands ###
