"""add username column to users table

Revision ID: 71b31e7f778a
Revises: b1684444ac94
Create Date: 2026-06-06 15:21:58.554913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b31e7f778a'
down_revision: Union[str, Sequence[str], None] = 'b1684444ac94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_last_read_message', 'conversation_members', 'messages', ['last_read_message_id'], ['id'], use_alter=True)
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_constraint('fk_last_read_message', 'conversation_members', type_='foreignkey')
    # ### end Alembic commands ###
