"""update posts and comments table

Revision ID: 8d4fe33b7ad7
Revises: a8421678f906
Create Date: 2026-02-25 20:09:45.138603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4fe33b7ad7'
down_revision: Union[str, Sequence[str], None] = 'a8421678f906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('publish_date', sa.DateTime(), nullable=False))
    op.add_column('posts', sa.Column('publish_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'publish_date')
    op.drop_column('comments', 'publish_date')
    # ### end Alembic commands ###
