"""add signup-date to user table

Revision ID: a684dc00d413
Revises: 3e5c2bb371c6
Create Date: 2025-11-15 20:26:53.540897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a684dc00d413'
down_revision: Union[str, Sequence[str], None] = '3e5c2bb371c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signup_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signup_date')
    # ### end Alembic commands ###
