"""users update

Revision ID: ba936bef7016
Revises: a684dc00d413
Create Date: 2025-11-19 20:40:15.479454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba936bef7016'
down_revision: Union[str, Sequence[str], None] = 'a684dc00d413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile', sa.String(), nullable=True, max_length=100))
    op.add_column('users', sa.Column('experience', sa.DECIMAL(precision=5, scale=1), nullable=True))
    op.drop_column('users', 'signup_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signup_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'experience')
    op.drop_column('users', 'profile')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
