"""update tables

Revision ID: efa3159a640d
Revises: 8d4fe33b7ad7
Create Date: 2026-02-28 23:40:29.472208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa3159a640d'
down_revision: Union[str, Sequence[str], None] = '8d4fe33b7ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_categories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.create_index(op.f('ix_posts_publish_date'), 'posts', ['publish_date'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_posts_publish_date'), table_name='posts')
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_column('comments', 'user_id')
    op.drop_table('user_categories')
    # ### end Alembic commands ###
